In [2]:
import numpy as np

In [3]:
np.__version__

'2.4.6'

In [4]:
my_list = [2,4,5,6,7,8]
my_list

[2, 4, 5, 6, 7, 8]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([2, 4, 5, 6, 7, 8])

In [7]:
type(arr)

numpy.ndarray

In [8]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [11]:
np.arrange([-20,10])

AttributeError: module 'numpy' has no attribute 'arrange'

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
np.random.randint(2)

1

In [21]:
np.random.rand(2,3)

array([[0.48438178, 0.3239705 , 0.50931636],
       [0.0125426 , 0.32924401, 0.05176192]])

In [33]:
np.random.randint(2,9,4)

array([5, 3, 5, 4], dtype=int32)

In [36]:
np.random.randint(10,40,(10,10),dtype=int)

array([[10, 21, 17, 21, 19, 12, 25, 21, 28, 14],
       [38, 24, 35, 12, 25, 24, 18, 13, 34, 25],
       [24, 25, 14, 33, 34, 39, 39, 10, 39, 32],
       [34, 30, 22, 13, 33, 20, 32, 17, 25, 16],
       [12, 22, 37, 33, 14, 33, 12, 33, 25, 37],
       [21, 23, 16, 36, 29, 27, 18, 30, 11, 30],
       [36, 25, 11, 33, 23, 14, 16, 39, 12, 22],
       [16, 39, 35, 37, 23, 25, 18, 27, 39, 17],
       [30, 15, 35, 15, 11, 27, 14, 35, 28, 31],
       [27, 36, 22, 38, 36, 24, 36, 32, 14, 39]], dtype=int32)

In [1]:
import numpy as np

In [2]:
mylist = [55,33,22,1,35,21,3]

In [3]:
arr1 = mylist

In [4]:
arr1

[55, 33, 22, 1, 35, 21, 3]

In [6]:
np.sort(arr1)

array([ 1,  3, 21, 22, 33, 35, 55])

In [8]:
np.zeros(7, dtype = int)

array([0, 0, 0, 0, 0, 0, 0])

In [9]:
type(arr1)

list

In [28]:
import numpy as np
np.random.randint(1,100,(10,10))
np.arange(1,10)
print(type(np.arange(1,10)))
                    

            

<class 'numpy.ndarray'>


In [30]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
A