Array Creation Functions

In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3])

In [6]:
print('array a:',a)

array a: [1 2 3]


In [7]:
b = np.arange(0,10,3)
print('array b:', b)

array b: [0 3 6 9]


In [9]:
z= np.zeros([2,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
d = np.zeros((2,3),dtype=int)
print(d)

[[0 0 0]
 [0 0 0]]


In [15]:
e = np.ones((3,2),dtype = int)
print('array e:\n', e)

array e:
 [[1 1]
 [1 1]
 [1 1]]


In [18]:
f = np.eye(4) #diagonals are same
print('identity matrix:\n', f)

identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


ARRAY MANIPULATION

In [21]:
import numpy as np

In [24]:
a1 = np.array([1,2,3])

In [28]:
reshaped = np.reshape(a1,(1,3))
print('reshaped array:', reshaped)

reshaped array: [[1 2 3]]


In [29]:
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [30]:
flattend = np.ravel(f1)

In [31]:
print(flattend)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
print(f1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [33]:
t1 = np.array([[1,2],[3,4]])

In [34]:
transposed = np.transpose(t1)

In [36]:
print(transposed)

[[1 3]
 [2 4]]


In [37]:
print(t1)

[[1 2]
 [3 4]]


In [38]:
a2 = np.array([1,2])
b2 = np.array([3,4])

In [39]:
stacked = np.vstack([a2,b2])
print(stacked) #vertical stack

[[1 2]
 [3 4]]


In [41]:
stackedh = np.hstack([a2,b2])
print(stackedh)#horizontal stack

[1 2 3 4]


Mathematical Functions


In [44]:
g = np.array([1,2,3,4])
added = np.add(g,2)
print('added 2 to g:', added)

added 2 to g: [3 4 5 6]


In [45]:
squared = np.power(g,2)
print(squared)

[ 1  4  9 16]


In [46]:
sqrt_root = np.sqrt(g)
print(sqrt_root)

[1.         1.41421356 1.73205081 2.        ]


In [47]:
print(a)

[1 2 3]


In [48]:
print(g)

[1 2 3 4]


In [49]:
dot_product = np.dot(a,g)
print(dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [52]:
a1 = np.array([1,2,3])

In [53]:
dot_product = np.dot(a1,a)
print(dot_product)

14


Statistical Numpy


In [54]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print(mean)

2.5


In [55]:
var = np.var(s)
print('variance:',var)

variance: 1.25


In [56]:
std_dev = np.std(s)
print('standard deviation of s:', std_dev)

standard deviation of s: 1.118033988749895


In [57]:
print(s)

[1 2 3 4]


In [58]:
mini = np.min(s)
print(mini)

1


In [59]:
maxx = np.max(s)
print(maxx)

4


Random sampling

In [60]:
random_vals = np.random.rand(3)
print('random values:', random_vals)

random values: [0.4835505  0.95674777 0.53564318]


In [61]:
rand_int = np.random.randint(0,10, size = 5)
print(rand_int)

[6 9 5 0 5]


In [78]:
np.random.seed(0)
rand_int1 = np.random.randint(1,10, size =5)
print(rand_int1)

[6 1 4 4 8]


In [1]:
import numpy as np

In [15]:
arr = np.arange(0,100).reshape(10,10)

In [16]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
logical_test = np.array([True, True,True])
result = np.all(logical_test)
print(result)

True


In [28]:
logical_test1 = np.array([True, False,True])
result = np.all(logical_test1) #if all elements are true then result is true
print(result)

False


In [30]:
result1 = np.any(logical_test1)
print(result1) #if any element is true than its true

True


In [31]:
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [32]:
union = np.union1d(set_a,set_b)
print(union)

[1 2 3 4 5 6]


ARRAY ATTRIBUTES 

In [34]:
a = np.array([2,3,4])

In [35]:
shape = a.shape
size = a.size
dimensions = a.ndim
dtype = a.dtype

In [37]:
print(shape)
print(size)
print(dimensions)
print(dtype)

(3,)
3
1
int64


In [38]:
a1 = np.transpose(a)

In [39]:
print(a1)

[2 3 4]


In [42]:
a1 = np.reshape(a, (3,1))

In [43]:
a1

array([[2],
       [3],
       [4]])

In [45]:
copied = np.copy(a1)
print(copied)

[[2]
 [3]
 [4]]


In [46]:
byte = a.nbytes
print(byte)

24
